libs:
  - https://poggit.pmmp.io/r/181115/await-generator_dev-92.phar
  - https://poggit.pmmp.io/r/189496/libasynql_dev-180.phar
  - https://poggit.pmmp.io/r/189672/InvMenu_dev-1.phar
  - https://poggit.pmmp.io/r/162403/UpdateNotifier_dev-13.phar
  - https://poggit.pmmp.io/r/148280/Commando_dev-43.phar