---
projects:
  AuctionHouse:
    path: ""
    icon: icon.png
    libs:
    - src: SOF3/await-generator/await-generator
      version: ^3.1.0
    - src: poggit/libasynql/libasynql
      version: ^3.4.0
    - src: brokiem-pm-pl/InvMenu/InvMenu
      version: ^4.4.1
      branch: "4.0"
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.2.0
      branch: API-4.0.0
    - src: CortexPE/Commando/Commando
      version: ^3.0.0
      branch: PM4
...
